latest
Signed-off-by: James O. D. Hunt <jamesodhunt@gmail.com>

diff --git a/.github/workflows/pr-require-porting-labels.yaml b/.github/workflows/pr-require-porting-labels.yaml
--- a/.github/workflows/pr-require-porting-labels.yaml
+++ b/.github/workflows/pr-require-porting-labels.yaml
@@ -38,8 +38,8 @@ jobs:
           # Every PR must have two porting labels before it can be merged.
           # This is to ensure it is clear that a reviewer has considered both
           # porting directions.
-          backport_labels=("needs-backport" "no-backport-needed")
-          forward_port_labels=("needs-forward-port" "no-forward-port-needed")
+          backport_labels=("needs-backport" "no-backport-needed" "backport-pr")
+          forward_port_labels=("needs-forward-port" "no-forward-port-needed" "forward-port-pr")
 
           labels=$(hub api "/repos/{owner}/{repo}/labels" | jq -r '.[].name')
 
@@ -47,21 +47,28 @@ jobs:
           do
             { echo "$labels"| egrep -q "^${label}$"; ret=$?; } || true
 
-            [ $ret -eq 0 ] || \
-              { echo "::error::Repo ${{ github.repository }} missing label '$label'" && exit 1; }
+            [ $ret -eq 0 ] || {
+              echo "::error::Expected label '$label' not available in repository ${{ github.repository }}"
+              exit 1
+            }
           done
 
           pr_details=$(hub pr list -f '%I;%L%n' | grep "^${pr}" || true)
 
-          [ -z "$pr_details" ] \
-            && echo "::error::Cannot determine details for PR $pr" \
-            && exit 1
+          [ -z "$pr_details" ] && {
+            echo "::error::Cannot determine details for PR $pr"
+            exit 1
+          }
 
           pr_labels=$(echo "$pr_details"|cut -d';' -f2|tr ',' ' ')
 
-          [ -z "$pr_labels" ] \
-            && echo "::error::PR $pr does not have required porting labels" \
-            && exit 1
+          [ -z "$pr_labels" ] && {
+            printf "::error::PR %s does not have required porting labels (expected one of '%s' and one of '%s')\n" \
+                   "$pr" \
+                   $(echo "${backport_labels[@]}" | tr ' ' ',') \
+                   $(echo "${forward_port_labels[@]}" | tr ' ' ',')
+            exit 1
+          }
 
           backport_labels_found=()
 
@@ -71,13 +78,20 @@ jobs:
               && backport_labels_found+=("$label")
           done
 
-          [ "${#backport_labels_found[@]}" -eq 0 ] \
-            && echo "::error::PR $pr missing a backport label (${backport_labels[@]})" \
-            && exit 1
+          [ "${#backport_labels_found[@]}" -eq 0 ] && {
+            printf "::error::PR %s missing a backport label (expected one of '%s')\n" \
+                   "$pr" \
+                   $(echo "${backport_labels[@]})" | tr ' ' ',')
+            exit 1
+          }
 
-          [ "${#backport_labels_found[@]}" -gt 1 ] \
-            && echo "::error::PR $pr has too many backport labels set (${backport_labels_found[@]})" \
-            && exit 1
+          [ "${#backport_labels_found[@]}" -gt 1 ] && {
+            printf "::error::PR %s has too many backport labels (expected one of '%s', found '%s')\n" \
+                   "$pr" \
+                   $(echo "${backport_labels[@]})" | tr ' ' ',') \
+                   $(echo "${backport_labels_found[@]}" | tr ' ' ',')
+            exit 1
+          }
 
           forward_port_labels_found=()
 
@@ -87,12 +101,22 @@ jobs:
               && forward_port_labels_found+=("$label")
           done
 
-          [ "${#forward_port_labels_found[@]}" -eq 0 ] \
-            && echo "::error::PR $pr missing a forward port label (${forward_port_labels[@]})" \
-            && exit 1
+          [ "${#forward_port_labels_found[@]}" -eq 0 ] && {
+            printf "::error::PR %s missing a forward port label (expected one of '%s')\n" \
+                    "$pr" \
+                    $(echo "${forward_port_labels[@]}" | tr ' ' ',')
+            exit 1
+          }
 
-          [ "${#forward_port_labels_found[@]}" -gt 1 ] \
-            && echo "::error::PR $pr has too many forward port labels set (${forward_port_labels_found[@]})" \
-            && exit 1
+          [ "${#forward_port_labels_found[@]}" -gt 1 ] && {
+            printf "::error::PR %s has too many forward port labels (expected one of '%s', found '%s')\n" \
+                    "$pr" \
+                    $(echo "${forward_port_labels[@]})" | tr ' ' ',') \
+                    $(echo "${forward_port_labels_found[@]}" | tr ' ' ',')
+            exit 1
+          }
 
-          echo "::debug::PR $pr has required porting labels (${backport_labels_found[@]}, ${forward_port_labels_found[@]})"
+          printf "::debug::PR %s has required porting labels (backport label '%s', forward port label '%s')\n" \
+                  "$pr" \
+                  "${backport_labels_found[@]})" \
+                  "${forward_port_labels_found[@]}"
